plugins {
    id 'java'
    id 'war'
}

group = 'com.andey20005.web3'
version = '1'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly 'jakarta.platform:jakarta.jakartaee-api:10.0.0'

    implementation 'org.primefaces:primefaces:15.0.0:jakarta'
}

test {
    useJUnitPlatform()
}
